// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/snyk/go-application-framework/pkg/apiclients/fileupload (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -package fileuploadmock -destination fileuploadmock/client_mock.go github.com/snyk/go-application-framework/pkg/apiclients/fileupload Client
//

// Package fileuploadmock is a generated GoMock package.
package fileuploadmock

import (
	context "context"
	reflect "reflect"

	fileupload "github.com/snyk/go-application-framework/pkg/apiclients/fileupload"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CreateRevisionFromChan mocks base method.
func (m *MockClient) CreateRevisionFromChan(ctx context.Context, paths <-chan string, rootPath string) (fileupload.UploadResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRevisionFromChan", ctx, paths, rootPath)
	ret0, _ := ret[0].(fileupload.UploadResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRevisionFromChan indicates an expected call of CreateRevisionFromChan.
func (mr *MockClientMockRecorder) CreateRevisionFromChan(ctx, paths, rootPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRevisionFromChan", reflect.TypeOf((*MockClient)(nil).CreateRevisionFromChan), ctx, paths, rootPath)
}
