linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofumpt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacebloat
    - lll
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wrapcheck
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: true
  exhaustive:
    default-signifies-exhaustive: true
  goconst:
    ignore-calls: false
    min-occurrences: 5
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 15
  gofumpt:
    module-path: github.com/snyk/cli-extension-ai-bom
    extra-rules: true
  goimports:
    local-prefixes: github.com/snyk/cli-extension-ai-bom
  gosimple:
    checks: ["all"]
  govet:
    enable-all: true
    disable:
      - fieldalignment
  lll:
    line-length: 160
  misspell:
    locale: US
  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: true
  prealloc:
    simple: true
    range-loops: true
    for-loops: true
  promlinter:
    strict: true
  revive:
    rules:
      - name: blank-imports
        disabled: true
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
        disabled: true # Requires all error messages to start with lower case characters. This conflicts with Snyk's public error message standards.
      - name: error-naming
      - name: exported
        arguments:
          - "disableChecksOnConstants"
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
        disabled: true
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
  staticcheck:
    checks: ["all"]
  stylecheck:
    checks: ["all", "-ST1005"] # ST1005 requires all error messages to start with lower case characters. This conflicts with Snyk's public error message standards.
    http-status-code-whitelist: []

# NOTE(pkey): Can't change the return types so ignoring.
issues:
  exclude-rules:
