// Package aibomclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package aibomclient

import (
	"encoding/json"
	"errors"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CreateAndUploadAiBomFileBundleDataType.
const (
	CreateAndUploadAiBomFileBundleDataTypeAiBomFileBundle CreateAndUploadAiBomFileBundleDataType = "ai_bom_file_bundle"
)

// Defines values for CreateAndUploadAiBomFileUploadDataType.
const (
	CreateAndUploadAiBomFileUploadDataTypeAiBomFileUpload CreateAndUploadAiBomFileUploadDataType = "ai_bom_file_upload"
)

// Defines values for FileBundleStoreDataType.
const (
	FileBundleStoreDataTypeAiBomFileBundle FileBundleStoreDataType = "ai_bom_file_bundle"
)

// Defines values for FileUploadAPIDataType.
const (
	FileUploadAPIDataTypeAiBomFileUpload FileUploadAPIDataType = "ai_bom_file_upload"
)

// Defines values for GetAiBomResponseDataType.
const (
	GetAiBomResponseDataTypeAiBom GetAiBomResponseDataType = "ai_bom"
)

// Defines values for JobDataType.
const (
	JobDataTypeAiBomJob JobDataType = "ai_bom_job"
)

// Defines values for JobState.
const (
	JobStateErrored    JobState = "errored"
	JobStateFinished   JobState = "finished"
	JobStateProcessing JobState = "processing"
)

// Defines values for SCMBundleStoreDataType.
const (
	SCMBundleStoreDataTypeAiBomSCMBundle SCMBundleStoreDataType = "ai_bom_scm_bundle"
)

// ActualVersion Resolved API version
type ActualVersion = string

// AiBomAttributes The AI-Bom document
type AiBomAttributes map[string]interface{}

// CreateAiBomRequestBody defines model for CreateAiBomRequestBody.
type CreateAiBomRequestBody struct {
	Data CreateAiBomRequestData `json:"data"`
}

// CreateAiBomRequestData defines model for CreateAiBomRequestData.
type CreateAiBomRequestData struct {
	union json.RawMessage
}

// CreateAiBomResponseBody defines model for CreateAiBomResponseBody.
type CreateAiBomResponseBody struct {
	Data    JobData        `json:"data"`
	Jsonapi JSONAPI        `json:"jsonapi"`
	Links   PaginatedLinks `json:"links"`
}

// CreateAndUploadAiBomFileBundleAttributes defines model for CreateAndUploadAiBomFileBundleAttributes.
type CreateAndUploadAiBomFileBundleAttributes struct {
	// BundleID The id of the bundle that has been uploaded by the user, sha256 hash
	BundleID string `json:"bundle_id"`

	// RepoName The name of the repository
	RepoName string `json:"repo_name"`
}

// CreateAndUploadAiBomFileBundleData defines model for CreateAndUploadAiBomFileBundleData.
type CreateAndUploadAiBomFileBundleData struct {
	Attributes CreateAndUploadAiBomFileBundleAttributes `json:"attributes"`
	Type       CreateAndUploadAiBomFileBundleDataType   `json:"type"`
}

// CreateAndUploadAiBomFileBundleDataType defines model for CreateAndUploadAiBomFileBundleData.Type.
type CreateAndUploadAiBomFileBundleDataType string

// CreateAndUploadAiBomFileUploadAttributes defines model for CreateAndUploadAiBomFileUploadAttributes.
type CreateAndUploadAiBomFileUploadAttributes struct {
	// RepoName The name of the repository
	RepoName string `json:"repo_name"`

	// UploadRevisionID The id of the upload revision the has been created by the user
	UploadRevisionID openapi_types.UUID `json:"upload_revision_id"`
}

// CreateAndUploadAiBomFileUploadData defines model for CreateAndUploadAiBomFileUploadData.
type CreateAndUploadAiBomFileUploadData struct {
	Attributes CreateAndUploadAiBomFileUploadAttributes `json:"attributes"`
	Type       CreateAndUploadAiBomFileUploadDataType   `json:"type"`
}

// CreateAndUploadAiBomFileUploadDataType defines model for CreateAndUploadAiBomFileUploadData.Type.
type CreateAndUploadAiBomFileUploadDataType string

// CreateAndUploadAiBomRequestBody defines model for CreateAndUploadAiBomRequestBody.
type CreateAndUploadAiBomRequestBody struct {
	Data CreateAndUploadAiBomRequestData `json:"data"`
}

// CreateAndUploadAiBomRequestData defines model for CreateAndUploadAiBomRequestData.
type CreateAndUploadAiBomRequestData struct {
	union json.RawMessage
}

// Error defines model for Error.
type Error struct {
	// Code An application-specific error code, expressed as a string value.
	Code *string `json:"code,omitempty"`

	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail string `json:"detail"`

	// ID A unique identifier for this particular occurrence of the problem.
	ID *openapi_types.UUID `json:"id,omitempty"`

	// Links A link that leads to further details about this particular occurrence of the problem.
	Links  *ErrorLink              `json:"links,omitempty"`
	Meta   *map[string]interface{} `json:"meta,omitempty"`
	Source *struct {
		// Parameter A string indicating which URI query parameter caused the error.
		Parameter *string `json:"parameter,omitempty"`

		// Pointer A JSON Pointer [RFC6901] to the associated entity in the request document.
		Pointer *string `json:"pointer,omitempty"`
	} `json:"source,omitempty"`

	// Status The HTTP status code applicable to this problem, expressed as a string value.
	Status string `json:"status"`

	// Title A short, human-readable summary of the problem that SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization.
	Title *string `json:"title,omitempty"`
}

// ErrorDocument defines model for ErrorDocument.
type ErrorDocument struct {
	Errors  []Error `json:"errors"`
	Jsonapi JSONAPI `json:"jsonapi"`
}

// ErrorLink A link that leads to further details about this particular occurrence of the problem.
type ErrorLink struct {
	About *LinkProperty `json:"about,omitempty"`
}

// FileBundleStoreAttributes defines model for FileBundleStoreAttributes.
type FileBundleStoreAttributes struct {
	// BundleID The id of the bundle that has been uploaded by the user, sha256 hash
	BundleID string `json:"bundle_id"`
}

// FileBundleStoreData defines model for FileBundleStoreData.
type FileBundleStoreData struct {
	Attributes FileBundleStoreAttributes `json:"attributes"`
	Type       FileBundleStoreDataType   `json:"type"`
}

// FileBundleStoreDataType defines model for FileBundleStoreData.Type.
type FileBundleStoreDataType string

// FileUploadAPIAttributes defines model for FileUploadApiAttributes.
type FileUploadAPIAttributes struct {
	// UploadRevisionID The id of the upload revision the has been created by the user
	UploadRevisionID openapi_types.UUID `json:"upload_revision_id"`
}

// FileUploadAPIData defines model for FileUploadApiData.
type FileUploadAPIData struct {
	Attributes FileUploadAPIAttributes `json:"attributes"`
	Type       FileUploadAPIDataType   `json:"type"`
}

// FileUploadAPIDataType defines model for FileUploadAPIData.Type.
type FileUploadAPIDataType string

// GetAiBomResponseBody defines model for GetAiBomResponseBody.
type GetAiBomResponseBody struct {
	Data    GetAiBomResponseData `json:"data"`
	Jsonapi JSONAPI              `json:"jsonapi"`
	Links   PaginatedLinks       `json:"links"`
}

// GetAiBomResponseData defines model for GetAiBomResponseData.
type GetAiBomResponseData struct {
	// Attributes The AI-Bom document
	Attributes AiBomAttributes          `json:"attributes"`
	ID         openapi_types.UUID       `json:"id"`
	Type       GetAiBomResponseDataType `json:"type"`
}

// GetAiBomResponseDataType defines model for GetAiBomResponseData.Type.
type GetAiBomResponseDataType string

// GetAiBomResponseJobBody defines model for GetAiBomResponseJobBody.
type GetAiBomResponseJobBody struct {
	Data    JobData        `json:"data"`
	Jsonapi JSONAPI        `json:"jsonapi"`
	Links   PaginatedLinks `json:"links"`
}

// JobAttributes JobAttributes represents the attributes of a Job resource
type JobAttributes struct {
	// Status State of the job.
	Status JobState `json:"status"`
}

// JobData defines model for JobData.
type JobData struct {
	// Attributes JobAttributes represents the attributes of a Job resource
	Attributes    JobAttributes         `json:"attributes"`
	ID            openapi_types.UUID    `json:"id"`
	Relationships *JobDataRelationships `json:"relationships,omitempty"`
	Type          JobDataType           `json:"type"`
}

// JobDataType defines model for JobData.Type.
type JobDataType string

// JobDataRelationships defines model for JobDataRelationships.
type JobDataRelationships struct {
	AiBom RelationshipObjectToOne `json:"ai_bom"`
}

// JobState State of the job.
type JobState string

// JSONAPI defines model for JsonApi.
type JSONAPI struct {
	// Version Version of the JSON API specification this server supports.
	Version string `json:"version"`
}

// LinkProperty defines model for LinkProperty.
type LinkProperty struct {
	union json.RawMessage
}

// LinkProperty0 A string containing the link’s URL.
type LinkProperty0 = string

// LinkProperty1 defines model for .
type LinkProperty1 struct {
	// Href A string containing the link’s URL.
	Href string `json:"href"`

	// Meta Free-form object that may contain non-standard information.
	Meta *Meta `json:"meta,omitempty"`
}

// Meta Free-form object that may contain non-standard information.
type Meta map[string]interface{}

// PaginatedLinks defines model for PaginatedLinks.
type PaginatedLinks struct {
	First *LinkProperty `json:"first,omitempty"`
	Last  *LinkProperty `json:"last,omitempty"`
	Next  *LinkProperty `json:"next,omitempty"`
	Prev  *LinkProperty `json:"prev,omitempty"`
	Self  *LinkProperty `json:"self,omitempty"`
}

// QueryVersion Requested API version
type QueryVersion = string

// RelationshipObjectToOne defines model for RelationshipObjectToOne.
type RelationshipObjectToOne struct {
	Data RelationshipObjectToOneData `json:"data"`
}

// RelationshipObjectToOneData defines model for RelationshipObjectToOneData.
type RelationshipObjectToOneData struct {
	ID   openapi_types.UUID `json:"id"`
	Type string             `json:"type"`
}

// SCMBundleStoreAttributes defines model for ScmBundleStoreAttributes.
type SCMBundleStoreAttributes struct {
	// TargetID The id of the target which has been imported into Snyk.
	TargetID openapi_types.UUID `json:"target_id"`

	// TargetVersion The branch or commit hash to scan
	TargetVersion *string `json:"target_version,omitempty"`
}

// SCMBundleStoreData defines model for ScmBundleStoreData.
type SCMBundleStoreData struct {
	Attributes SCMBundleStoreAttributes `json:"attributes"`
	Type       SCMBundleStoreDataType   `json:"type"`
}

// SCMBundleStoreDataType defines model for SCMBundleStoreData.Type.
type SCMBundleStoreDataType string

// AiBomIDParam defines model for AiBomIdParam.
type AiBomIDParam = openapi_types.UUID

// JobIDParam defines model for JobIdParam.
type JobIDParam = openapi_types.UUID

// OrgIDParam defines model for OrgIdParam.
type OrgIDParam = openapi_types.UUID

// Version Requested API version
type Version = QueryVersion

// N400 defines model for 400.
type N400 = ErrorDocument

// N401 defines model for 401.
type N401 = ErrorDocument

// N404 defines model for 404.
type N404 = ErrorDocument

// N500 defines model for 500.
type N500 = ErrorDocument

// N503 defines model for 503.
type N503 = ErrorDocument

// GetAiBomJobParams defines parameters for GetAiBomJob.
type GetAiBomJobParams struct {
	// Version The requested version of the endpoint to process the request
	Version Version `form:"version" json:"version"`
}

// CreateAiBomParams defines parameters for CreateAiBom.
type CreateAiBomParams struct {
	// Version The requested version of the endpoint to process the request
	Version Version `form:"version" json:"version"`
}

// CreateAndUploadAiBomParams defines parameters for CreateAndUploadAiBom.
type CreateAndUploadAiBomParams struct {
	// Version The requested version of the endpoint to process the request
	Version Version `form:"version" json:"version"`
}

// GetAiBomParams defines parameters for GetAiBom.
type GetAiBomParams struct {
	// Version The requested version of the endpoint to process the request
	Version Version `form:"version" json:"version"`
}

// CreateAiBomApplicationVndAPIPlusJSONRequestBody defines body for CreateAiBom for application/vnd.api+json ContentType.
type CreateAiBomApplicationVndAPIPlusJSONRequestBody = CreateAiBomRequestBody

// CreateAndUploadAiBomApplicationVndAPIPlusJSONRequestBody defines body for CreateAndUploadAiBom for application/vnd.api+json ContentType.
type CreateAndUploadAiBomApplicationVndAPIPlusJSONRequestBody = CreateAndUploadAiBomRequestBody

// AsFileBundleStoreData returns the union data inside the CreateAiBomRequestData as a FileBundleStoreData
func (t CreateAiBomRequestData) AsFileBundleStoreData() (FileBundleStoreData, error) {
	var body FileBundleStoreData
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFileBundleStoreData overwrites any union data inside the CreateAiBomRequestData as the provided FileBundleStoreData
func (t *CreateAiBomRequestData) FromFileBundleStoreData(v FileBundleStoreData) error {
	v.Type = "ai_bom_file_bundle"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFileBundleStoreData performs a merge with any union data inside the CreateAiBomRequestData, using the provided FileBundleStoreData
func (t *CreateAiBomRequestData) MergeFileBundleStoreData(v FileBundleStoreData) error {
	v.Type = "ai_bom_file_bundle"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSCMBundleStoreData returns the union data inside the CreateAiBomRequestData as a SCMBundleStoreData
func (t CreateAiBomRequestData) AsSCMBundleStoreData() (SCMBundleStoreData, error) {
	var body SCMBundleStoreData
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSCMBundleStoreData overwrites any union data inside the CreateAiBomRequestData as the provided SCMBundleStoreData
func (t *CreateAiBomRequestData) FromSCMBundleStoreData(v SCMBundleStoreData) error {
	v.Type = "ai_bom_scm_bundle"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSCMBundleStoreData performs a merge with any union data inside the CreateAiBomRequestData, using the provided SCMBundleStoreData
func (t *CreateAiBomRequestData) MergeSCMBundleStoreData(v SCMBundleStoreData) error {
	v.Type = "ai_bom_scm_bundle"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFileUploadAPIData returns the union data inside the CreateAiBomRequestData as a FileUploadAPIData
func (t CreateAiBomRequestData) AsFileUploadAPIData() (FileUploadAPIData, error) {
	var body FileUploadAPIData
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFileUploadAPIData overwrites any union data inside the CreateAiBomRequestData as the provided FileUploadAPIData
func (t *CreateAiBomRequestData) FromFileUploadAPIData(v FileUploadAPIData) error {
	v.Type = "ai_bom_file_upload"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFileUploadAPIData performs a merge with any union data inside the CreateAiBomRequestData, using the provided FileUploadAPIData
func (t *CreateAiBomRequestData) MergeFileUploadAPIData(v FileUploadAPIData) error {
	v.Type = "ai_bom_file_upload"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CreateAiBomRequestData) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t CreateAiBomRequestData) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "ai_bom_file_bundle":
		return t.AsFileBundleStoreData()
	case "ai_bom_file_upload":
		return t.AsFileUploadAPIData()
	case "ai_bom_scm_bundle":
		return t.AsSCMBundleStoreData()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t CreateAiBomRequestData) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CreateAiBomRequestData) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsCreateAndUploadAiBomFileBundleData returns the union data inside the CreateAndUploadAiBomRequestData as a CreateAndUploadAiBomFileBundleData
func (t CreateAndUploadAiBomRequestData) AsCreateAndUploadAiBomFileBundleData() (CreateAndUploadAiBomFileBundleData, error) {
	var body CreateAndUploadAiBomFileBundleData
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCreateAndUploadAiBomFileBundleData overwrites any union data inside the CreateAndUploadAiBomRequestData as the provided CreateAndUploadAiBomFileBundleData
func (t *CreateAndUploadAiBomRequestData) FromCreateAndUploadAiBomFileBundleData(v CreateAndUploadAiBomFileBundleData) error {
	v.Type = "ai_bom_file_bundle"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCreateAndUploadAiBomFileBundleData performs a merge with any union data inside the CreateAndUploadAiBomRequestData, using the provided CreateAndUploadAiBomFileBundleData
func (t *CreateAndUploadAiBomRequestData) MergeCreateAndUploadAiBomFileBundleData(v CreateAndUploadAiBomFileBundleData) error {
	v.Type = "ai_bom_file_bundle"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCreateAndUploadAiBomFileUploadData returns the union data inside the CreateAndUploadAiBomRequestData as a CreateAndUploadAiBomFileUploadData
func (t CreateAndUploadAiBomRequestData) AsCreateAndUploadAiBomFileUploadData() (CreateAndUploadAiBomFileUploadData, error) {
	var body CreateAndUploadAiBomFileUploadData
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCreateAndUploadAiBomFileUploadData overwrites any union data inside the CreateAndUploadAiBomRequestData as the provided CreateAndUploadAiBomFileUploadData
func (t *CreateAndUploadAiBomRequestData) FromCreateAndUploadAiBomFileUploadData(v CreateAndUploadAiBomFileUploadData) error {
	v.Type = "ai_bom_file_upload"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCreateAndUploadAiBomFileUploadData performs a merge with any union data inside the CreateAndUploadAiBomRequestData, using the provided CreateAndUploadAiBomFileUploadData
func (t *CreateAndUploadAiBomRequestData) MergeCreateAndUploadAiBomFileUploadData(v CreateAndUploadAiBomFileUploadData) error {
	v.Type = "ai_bom_file_upload"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CreateAndUploadAiBomRequestData) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t CreateAndUploadAiBomRequestData) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "ai_bom_file_bundle":
		return t.AsCreateAndUploadAiBomFileBundleData()
	case "ai_bom_file_upload":
		return t.AsCreateAndUploadAiBomFileUploadData()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t CreateAndUploadAiBomRequestData) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CreateAndUploadAiBomRequestData) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsLinkProperty0 returns the union data inside the LinkProperty as a LinkProperty0
func (t LinkProperty) AsLinkProperty0() (LinkProperty0, error) {
	var body LinkProperty0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLinkProperty0 overwrites any union data inside the LinkProperty as the provided LinkProperty0
func (t *LinkProperty) FromLinkProperty0(v LinkProperty0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLinkProperty0 performs a merge with any union data inside the LinkProperty, using the provided LinkProperty0
func (t *LinkProperty) MergeLinkProperty0(v LinkProperty0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsLinkProperty1 returns the union data inside the LinkProperty as a LinkProperty1
func (t LinkProperty) AsLinkProperty1() (LinkProperty1, error) {
	var body LinkProperty1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLinkProperty1 overwrites any union data inside the LinkProperty as the provided LinkProperty1
func (t *LinkProperty) FromLinkProperty1(v LinkProperty1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLinkProperty1 performs a merge with any union data inside the LinkProperty, using the provided LinkProperty1
func (t *LinkProperty) MergeLinkProperty1(v LinkProperty1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t LinkProperty) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *LinkProperty) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
