// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/snyk/cli-extension-ai-bom/internal/services/red-team-client (interfaces: RedTeamClient)
//
// Generated by this command:
//
//	mockgen -package redteamclientmock -destination mocks/redteamclientmock/client_mock.go github.com/snyk/cli-extension-ai-bom/internal/services/red-team-client RedTeamClient
//

// Package redteamclientmock is a generated GoMock package.
package redteamclientmock

import (
	context "context"
	reflect "reflect"

	redteamclient "github.com/snyk/cli-extension-ai-bom/internal/services/red-team-client"
	snyk_errors "github.com/snyk/error-catalog-golang-public/snyk_errors"
	gomock "go.uber.org/mock/gomock"
)

// MockRedTeamClient is a mock of RedTeamClient interface.
type MockRedTeamClient struct {
	ctrl     *gomock.Controller
	recorder *MockRedTeamClientMockRecorder
	isgomock struct{}
}

// MockRedTeamClientMockRecorder is the mock recorder for MockRedTeamClient.
type MockRedTeamClientMockRecorder struct {
	mock *MockRedTeamClient
}

// NewMockRedTeamClient creates a new mock instance.
func NewMockRedTeamClient(ctrl *gomock.Controller) *MockRedTeamClient {
	mock := &MockRedTeamClient{ctrl: ctrl}
	mock.recorder = &MockRedTeamClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedTeamClient) EXPECT() *MockRedTeamClientMockRecorder {
	return m.recorder
}

// CheckAPIAvailability mocks base method.
func (m *MockRedTeamClient) CheckAPIAvailability(ctx context.Context, orgID string) *snyk_errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAPIAvailability", ctx, orgID)
	ret0, _ := ret[0].(*snyk_errors.Error)
	return ret0
}

// CheckAPIAvailability indicates an expected call of CheckAPIAvailability.
func (mr *MockRedTeamClientMockRecorder) CheckAPIAvailability(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAPIAvailability", reflect.TypeOf((*MockRedTeamClient)(nil).CheckAPIAvailability), ctx, orgID)
}

// CreateScan mocks base method.
func (m *MockRedTeamClient) CreateScan(ctx context.Context, orgID string, config redteamclient.RedTeamConfig) (string, *snyk_errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateScan", ctx, orgID, config)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*snyk_errors.Error)
	return ret0, ret1
}

// CreateScan indicates an expected call of CreateScan.
func (mr *MockRedTeamClientMockRecorder) CreateScan(ctx, orgID, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateScan", reflect.TypeOf((*MockRedTeamClient)(nil).CreateScan), ctx, orgID, config)
}

// GetScan mocks base method.
func (m *MockRedTeamClient) GetScan(ctx context.Context, orgID, scanID string) (*redteamclient.ScanStatus, *snyk_errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScan", ctx, orgID, scanID)
	ret0, _ := ret[0].(*redteamclient.ScanStatus)
	ret1, _ := ret[1].(*snyk_errors.Error)
	return ret0, ret1
}

// GetScan indicates an expected call of GetScan.
func (mr *MockRedTeamClientMockRecorder) GetScan(ctx, orgID, scanID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScan", reflect.TypeOf((*MockRedTeamClient)(nil).GetScan), ctx, orgID, scanID)
}

// GetScanResults mocks base method.
func (m *MockRedTeamClient) GetScanResults(ctx context.Context, orgID, scanID string) (string, *snyk_errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScanResults", ctx, orgID, scanID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*snyk_errors.Error)
	return ret0, ret1
}

// GetScanResults indicates an expected call of GetScanResults.
func (mr *MockRedTeamClientMockRecorder) GetScanResults(ctx, orgID, scanID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScanResults", reflect.TypeOf((*MockRedTeamClient)(nil).GetScanResults), ctx, orgID, scanID)
}

// ListScans mocks base method.
func (m *MockRedTeamClient) ListScans(ctx context.Context, orgID string) ([]redteamclient.ScanSummary, *snyk_errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListScans", ctx, orgID)
	ret0, _ := ret[0].([]redteamclient.ScanSummary)
	ret1, _ := ret[1].(*snyk_errors.Error)
	return ret0, ret1
}

// ListScans indicates an expected call of ListScans.
func (mr *MockRedTeamClientMockRecorder) ListScans(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListScans", reflect.TypeOf((*MockRedTeamClient)(nil).ListScans), ctx, orgID)
}
