// Package fileuploadapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package fileuploadapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for UploadRevisionPostRequest20241015DataAttributesRevisionType.
const (
	UploadRevisionPostRequest20241015DataAttributesRevisionTypeSnapshot UploadRevisionPostRequest20241015DataAttributesRevisionType = "snapshot"
)

// Defines values for UploadRevisionPostRequest20241015DataType.
const (
	UploadRevisionPostRequest20241015DataTypeUploadRevision UploadRevisionPostRequest20241015DataType = "upload_revision"
)

// Defines values for UploadRevisionPostResponse20241015DataAttributesRevisionType.
const (
	UploadRevisionPostResponse20241015DataAttributesRevisionTypeSnapshot UploadRevisionPostResponse20241015DataAttributesRevisionType = "snapshot"
)

// Defines values for UploadRevisionPostResponse20241015DataType.
const (
	UploadRevisionPostResponse20241015DataTypeUploadRevision UploadRevisionPostResponse20241015DataType = "upload_revision"
)

// Defines values for ContentEncodingHeader.
const (
	ContentEncodingHeaderGzip  ContentEncodingHeader = "gzip"
	ContentEncodingHeaderXGzip ContentEncodingHeader = "x-gzip"
)

// Defines values for JsonContentTypeHeader.
const (
	JsonContentTypeHeaderApplicationvndApiJson JsonContentTypeHeader = "application/vnd.api+json"
)

// Defines values for CreateUploadRevisionParamsContentType.
const (
	CreateUploadRevisionParamsContentTypeApplicationvndApiJson CreateUploadRevisionParamsContentType = "application/vnd.api+json"
)

// Defines values for CreateUploadRevisionParamsContentEncoding.
const (
	CreateUploadRevisionParamsContentEncodingGzip  CreateUploadRevisionParamsContentEncoding = "gzip"
	CreateUploadRevisionParamsContentEncodingXGzip CreateUploadRevisionParamsContentEncoding = "x-gzip"
)

// Defines values for UpdateUploadRevisionParamsContentType.
const (
	ApplicationvndApiJson UpdateUploadRevisionParamsContentType = "application/vnd.api+json"
)

// Defines values for UpdateUploadRevisionParamsContentEncoding.
const (
	UpdateUploadRevisionParamsContentEncodingGzip  UpdateUploadRevisionParamsContentEncoding = "gzip"
	UpdateUploadRevisionParamsContentEncodingXGzip UpdateUploadRevisionParamsContentEncoding = "x-gzip"
)

// Defines values for UpdateUploadRevisionApplicationVndAPIPlusJSONBodyDataType.
const (
	UploadRevision UpdateUploadRevisionApplicationVndAPIPlusJSONBodyDataType = "upload_revision"
)

// Defines values for CreateUploadRevisionFilesParamsContentEncoding.
const (
	CreateUploadRevisionFilesParamsContentEncodingGzip  CreateUploadRevisionFilesParamsContentEncoding = "gzip"
	CreateUploadRevisionFilesParamsContentEncodingXGzip CreateUploadRevisionFilesParamsContentEncoding = "x-gzip"
)

// ActualVersion Resolved API version
type ActualVersion = string

// ActualVersion0 Resolved API version
type ActualVersion0 = string

// Error defines model for Error.
type Error struct {
	// Code An application-specific error code, expressed as a string value.
	Code *string `json:"code,omitempty"`

	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail string `json:"detail"`

	// Id A unique identifier for this particular occurrence of the problem.
	Id *openapi_types.UUID `json:"id,omitempty"`

	// Links A link that leads to further details about this particular occurrance of the problem.
	Links  *ErrorLink              `json:"links,omitempty"`
	Meta   *map[string]interface{} `json:"meta,omitempty"`
	Source *struct {
		// Parameter A string indicating which URI query parameter caused the error.
		Parameter *string `json:"parameter,omitempty"`

		// Pointer A JSON Pointer [RFC6901] to the associated entity in the request document.
		Pointer *string `json:"pointer,omitempty"`
	} `json:"source,omitempty"`

	// Status The HTTP status code applicable to this problem, expressed as a string value.
	Status string `json:"status"`

	// Title A short, human-readable summary of the problem that SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization.
	Title *string `json:"title,omitempty"`
}

// ErrorDocument defines model for ErrorDocument.
type ErrorDocument struct {
	Errors  []Error `json:"errors"`
	Jsonapi JsonApi `json:"jsonapi"`
}

// ErrorLink A link that leads to further details about this particular occurrance of the problem.
type ErrorLink struct {
	About *LinkProperty `json:"about,omitempty"`
}

// JsonApi defines model for JsonApi.
type JsonApi struct {
	// Version Version of the JSON API specification this server supports.
	Version string `json:"version"`
}

// Link defines model for Link.
type Link struct {
	// Href A string containing the link’s URL.
	Href string `json:"href"`
}

// LinkProperty defines model for LinkProperty.
type LinkProperty struct {
	union json.RawMessage
}

// LinkProperty0 A string containing the link’s URL.
type LinkProperty0 = string

// LinkProperty1 defines model for .
type LinkProperty1 struct {
	// Href A string containing the link’s URL.
	Href string `json:"href"`

	// Meta Free-form object that may contain non-standard information.
	Meta *Meta `json:"meta,omitempty"`
}

// LinkSelf defines model for LinkSelf.
type LinkSelf struct {
	Self Link `json:"self"`
}

// Meta Free-form object that may contain non-standard information.
type Meta map[string]interface{}

// QueryVersion Requested API version
type QueryVersion = string

// QueryVersion0 Requested API version
type QueryVersion0 = string

// UploadRevisionPostRequest20241015 defines model for UploadRevisionPostRequest_2024_10_15.
type UploadRevisionPostRequest20241015 struct {
	Data struct {
		Attributes struct {
			RevisionType UploadRevisionPostRequest20241015DataAttributesRevisionType `json:"revision_type"`
		} `json:"attributes"`
		Type UploadRevisionPostRequest20241015DataType `json:"type"`
	} `json:"data"`
}

// UploadRevisionPostRequest20241015DataAttributesRevisionType defines model for UploadRevisionPostRequest20241015.Data.Attributes.RevisionType.
type UploadRevisionPostRequest20241015DataAttributesRevisionType string

// UploadRevisionPostRequest20241015DataType defines model for UploadRevisionPostRequest20241015.Data.Type.
type UploadRevisionPostRequest20241015DataType string

// UploadRevisionPostResponse20241015 defines model for UploadRevisionPostResponse_2024_10_15.
type UploadRevisionPostResponse20241015 struct {
	Data struct {
		Attributes struct {
			RevisionType UploadRevisionPostResponse20241015DataAttributesRevisionType `json:"revision_type"`

			// Sealed The upload revision is sealed
			Sealed bool `json:"sealed"`
		} `json:"attributes"`

		// Id The upload revision identifier
		Id   openapi_types.UUID                         `json:"id"`
		Type UploadRevisionPostResponse20241015DataType `json:"type"`
	} `json:"data"`
	Jsonapi *JsonApi  `json:"jsonapi,omitempty"`
	Links   *LinkSelf `json:"links,omitempty"`
}

// UploadRevisionPostResponse20241015DataAttributesRevisionType defines model for UploadRevisionPostResponse20241015.Data.Attributes.RevisionType.
type UploadRevisionPostResponse20241015DataAttributesRevisionType string

// UploadRevisionPostResponse20241015DataType defines model for UploadRevisionPostResponse20241015.Data.Type.
type UploadRevisionPostResponse20241015DataType string

// ContentEncodingHeader defines model for ContentEncodingHeader.
type ContentEncodingHeader string

// JsonContentTypeHeader defines model for JsonContentTypeHeader.
type JsonContentTypeHeader string

// MultipartFormDataContentTypeHeader defines model for MultipartFormDataContentTypeHeader.
type MultipartFormDataContentTypeHeader = string

// OrgId defines model for OrgId.
type OrgId = openapi_types.UUID

// RequestId defines model for RequestId.
type RequestId = openapi_types.UUID

// UploadRevisionId defines model for UploadRevisionId.
type UploadRevisionId = openapi_types.UUID

// UserAgent defines model for UserAgent.
type UserAgent = string

// Version Requested API version
type Version = QueryVersion0

// N400 defines model for 400.
type N400 = ErrorDocument

// N4000 defines model for 400__0.
type N4000 = ErrorDocument

// N401 defines model for 401.
type N401 = ErrorDocument

// N4010 defines model for 401__0.
type N4010 = ErrorDocument

// N403 defines model for 403.
type N403 = ErrorDocument

// N404 defines model for 404.
type N404 = ErrorDocument

// N4040 defines model for 404__0.
type N4040 = ErrorDocument

// N500 defines model for 500.
type N500 = ErrorDocument

// N5000 defines model for 500__0.
type N5000 = ErrorDocument

// CreateUploadRevisionParams defines parameters for CreateUploadRevision.
type CreateUploadRevisionParams struct {
	// Version The requested version of the endpoint to process the request
	Version Version `form:"version" json:"version"`

	// SnykRequestId Unique ID used to track the request
	SnykRequestId *RequestId `json:"snyk-request-id,omitempty"`

	// UserAgent The client that sent the request, as per RFC 7231.
	UserAgent UserAgent `json:"user-agent"`

	// ContentType Content type header
	ContentType CreateUploadRevisionParamsContentType `json:"content-type"`

	// ContentEncoding Content encoding header for compressed request bodies
	ContentEncoding *CreateUploadRevisionParamsContentEncoding `json:"content-encoding,omitempty"`
}

// CreateUploadRevisionParamsContentType defines parameters for CreateUploadRevision.
type CreateUploadRevisionParamsContentType string

// CreateUploadRevisionParamsContentEncoding defines parameters for CreateUploadRevision.
type CreateUploadRevisionParamsContentEncoding string

// UpdateUploadRevisionApplicationVndAPIPlusJSONBody defines parameters for UpdateUploadRevision.
type UpdateUploadRevisionApplicationVndAPIPlusJSONBody struct {
	Data struct {
		Attributes struct {
			Sealed bool `json:"sealed"`
		} `json:"attributes"`

		// Id Upload Revision ID
		Id   openapi_types.UUID                                        `json:"id"`
		Type UpdateUploadRevisionApplicationVndAPIPlusJSONBodyDataType `json:"type"`
	} `json:"data"`
}

// UpdateUploadRevisionParams defines parameters for UpdateUploadRevision.
type UpdateUploadRevisionParams struct {
	// Version The requested version of the endpoint to process the request
	Version Version `form:"version" json:"version"`

	// SnykRequestId Unique ID used to track the request
	SnykRequestId *RequestId `json:"snyk-request-id,omitempty"`

	// UserAgent The client that sent the request, as per RFC 7231.
	UserAgent UserAgent `json:"user-agent"`

	// ContentType Content type header
	ContentType UpdateUploadRevisionParamsContentType `json:"content-type"`

	// ContentEncoding Content encoding header for compressed request bodies
	ContentEncoding *UpdateUploadRevisionParamsContentEncoding `json:"content-encoding,omitempty"`
}

// UpdateUploadRevisionParamsContentType defines parameters for UpdateUploadRevision.
type UpdateUploadRevisionParamsContentType string

// UpdateUploadRevisionParamsContentEncoding defines parameters for UpdateUploadRevision.
type UpdateUploadRevisionParamsContentEncoding string

// UpdateUploadRevisionApplicationVndAPIPlusJSONBodyDataType defines parameters for UpdateUploadRevision.
type UpdateUploadRevisionApplicationVndAPIPlusJSONBodyDataType string

// CreateUploadRevisionFilesMultipartBody defines parameters for CreateUploadRevisionFiles.
type CreateUploadRevisionFilesMultipartBody map[string]interface{}

// CreateUploadRevisionFilesParams defines parameters for CreateUploadRevisionFiles.
type CreateUploadRevisionFilesParams struct {
	// Version The requested version of the endpoint to process the request
	Version Version `form:"version" json:"version"`

	// SnykRequestId Unique ID used to track the request
	SnykRequestId *RequestId `json:"snyk-request-id,omitempty"`

	// UserAgent The client that sent the request, as per RFC 7231.
	UserAgent UserAgent `json:"user-agent"`

	// ContentType Multipart form content type header
	ContentType MultipartFormDataContentTypeHeader `json:"content-type"`

	// ContentEncoding Content encoding header for compressed request bodies
	ContentEncoding *CreateUploadRevisionFilesParamsContentEncoding `json:"content-encoding,omitempty"`
}

// CreateUploadRevisionFilesParamsContentEncoding defines parameters for CreateUploadRevisionFiles.
type CreateUploadRevisionFilesParamsContentEncoding string

// CreateUploadRevisionApplicationVndAPIPlusJSONRequestBody defines body for CreateUploadRevision for application/vnd.api+json ContentType.
type CreateUploadRevisionApplicationVndAPIPlusJSONRequestBody = UploadRevisionPostRequest20241015

// UpdateUploadRevisionApplicationVndAPIPlusJSONRequestBody defines body for UpdateUploadRevision for application/vnd.api+json ContentType.
type UpdateUploadRevisionApplicationVndAPIPlusJSONRequestBody UpdateUploadRevisionApplicationVndAPIPlusJSONBody

// CreateUploadRevisionFilesMultipartRequestBody defines body for CreateUploadRevisionFiles for multipart/form-data ContentType.
type CreateUploadRevisionFilesMultipartRequestBody CreateUploadRevisionFilesMultipartBody

// AsLinkProperty0 returns the union data inside the LinkProperty as a LinkProperty0
func (t LinkProperty) AsLinkProperty0() (LinkProperty0, error) {
	var body LinkProperty0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLinkProperty0 overwrites any union data inside the LinkProperty as the provided LinkProperty0
func (t *LinkProperty) FromLinkProperty0(v LinkProperty0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLinkProperty0 performs a merge with any union data inside the LinkProperty, using the provided LinkProperty0
func (t *LinkProperty) MergeLinkProperty0(v LinkProperty0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsLinkProperty1 returns the union data inside the LinkProperty as a LinkProperty1
func (t LinkProperty) AsLinkProperty1() (LinkProperty1, error) {
	var body LinkProperty1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLinkProperty1 overwrites any union data inside the LinkProperty as the provided LinkProperty1
func (t *LinkProperty) FromLinkProperty1(v LinkProperty1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLinkProperty1 performs a merge with any union data inside the LinkProperty, using the provided LinkProperty1
func (t *LinkProperty) MergeLinkProperty1(v LinkProperty1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t LinkProperty) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *LinkProperty) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListAPIVersions request
	ListAPIVersions(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAPIVersion request
	GetAPIVersion(ctx context.Context, version string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateUploadRevisionWithBody request with any body
	CreateUploadRevisionWithBody(ctx context.Context, orgId OrgId, params *CreateUploadRevisionParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateUploadRevisionWithApplicationVndAPIPlusJSONBody(ctx context.Context, orgId OrgId, params *CreateUploadRevisionParams, body CreateUploadRevisionApplicationVndAPIPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateUploadRevisionWithBody request with any body
	UpdateUploadRevisionWithBody(ctx context.Context, orgId OrgId, uploadRevisionId UploadRevisionId, params *UpdateUploadRevisionParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateUploadRevisionWithApplicationVndAPIPlusJSONBody(ctx context.Context, orgId OrgId, uploadRevisionId UploadRevisionId, params *UpdateUploadRevisionParams, body UpdateUploadRevisionApplicationVndAPIPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateUploadRevisionFilesWithBody request with any body
	CreateUploadRevisionFilesWithBody(ctx context.Context, orgId OrgId, uploadRevisionId UploadRevisionId, params *CreateUploadRevisionFilesParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListAPIVersions(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListAPIVersionsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAPIVersion(ctx context.Context, version string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAPIVersionRequest(c.Server, version)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateUploadRevisionWithBody(ctx context.Context, orgId OrgId, params *CreateUploadRevisionParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateUploadRevisionRequestWithBody(c.Server, orgId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateUploadRevisionWithApplicationVndAPIPlusJSONBody(ctx context.Context, orgId OrgId, params *CreateUploadRevisionParams, body CreateUploadRevisionApplicationVndAPIPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateUploadRevisionRequestWithApplicationVndAPIPlusJSONBody(c.Server, orgId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateUploadRevisionWithBody(ctx context.Context, orgId OrgId, uploadRevisionId UploadRevisionId, params *UpdateUploadRevisionParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateUploadRevisionRequestWithBody(c.Server, orgId, uploadRevisionId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateUploadRevisionWithApplicationVndAPIPlusJSONBody(ctx context.Context, orgId OrgId, uploadRevisionId UploadRevisionId, params *UpdateUploadRevisionParams, body UpdateUploadRevisionApplicationVndAPIPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateUploadRevisionRequestWithApplicationVndAPIPlusJSONBody(c.Server, orgId, uploadRevisionId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateUploadRevisionFilesWithBody(ctx context.Context, orgId OrgId, uploadRevisionId UploadRevisionId, params *CreateUploadRevisionFilesParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateUploadRevisionFilesRequestWithBody(c.Server, orgId, uploadRevisionId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListAPIVersionsRequest generates requests for ListAPIVersions
func NewListAPIVersionsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/openapi")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAPIVersionRequest generates requests for GetAPIVersion
func NewGetAPIVersionRequest(server string, version string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "version", runtime.ParamLocationPath, version)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/openapi/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateUploadRevisionRequestWithApplicationVndAPIPlusJSONBody calls the generic CreateUploadRevision builder with application/vnd.api+json body
func NewCreateUploadRevisionRequestWithApplicationVndAPIPlusJSONBody(server string, orgId OrgId, params *CreateUploadRevisionParams, body CreateUploadRevisionApplicationVndAPIPlusJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateUploadRevisionRequestWithBody(server, orgId, params, "application/vnd.api+json", bodyReader)
}

// NewCreateUploadRevisionRequestWithBody generates requests for CreateUploadRevision with any type of body
func NewCreateUploadRevisionRequestWithBody(server string, orgId OrgId, params *CreateUploadRevisionParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "org_id", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/orgs/%s/upload_revisions", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "version", runtime.ParamLocationQuery, params.Version); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.SnykRequestId != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "snyk-request-id", runtime.ParamLocationHeader, *params.SnykRequestId)
			if err != nil {
				return nil, err
			}

			req.Header.Set("snyk-request-id", headerParam0)
		}

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithLocation("simple", false, "user-agent", runtime.ParamLocationHeader, params.UserAgent)
		if err != nil {
			return nil, err
		}

		req.Header.Set("user-agent", headerParam1)

		var headerParam2 string

		headerParam2, err = runtime.StyleParamWithLocation("simple", false, "content-type", runtime.ParamLocationHeader, params.ContentType)
		if err != nil {
			return nil, err
		}

		req.Header.Set("content-type", headerParam2)

		if params.ContentEncoding != nil {
			var headerParam3 string

			headerParam3, err = runtime.StyleParamWithLocation("simple", false, "content-encoding", runtime.ParamLocationHeader, *params.ContentEncoding)
			if err != nil {
				return nil, err
			}

			req.Header.Set("content-encoding", headerParam3)
		}

	}

	return req, nil
}

// NewUpdateUploadRevisionRequestWithApplicationVndAPIPlusJSONBody calls the generic UpdateUploadRevision builder with application/vnd.api+json body
func NewUpdateUploadRevisionRequestWithApplicationVndAPIPlusJSONBody(server string, orgId OrgId, uploadRevisionId UploadRevisionId, params *UpdateUploadRevisionParams, body UpdateUploadRevisionApplicationVndAPIPlusJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateUploadRevisionRequestWithBody(server, orgId, uploadRevisionId, params, "application/vnd.api+json", bodyReader)
}

// NewUpdateUploadRevisionRequestWithBody generates requests for UpdateUploadRevision with any type of body
func NewUpdateUploadRevisionRequestWithBody(server string, orgId OrgId, uploadRevisionId UploadRevisionId, params *UpdateUploadRevisionParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "org_id", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "upload_revision_id", runtime.ParamLocationPath, uploadRevisionId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/orgs/%s/upload_revisions/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "version", runtime.ParamLocationQuery, params.Version); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.SnykRequestId != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "snyk-request-id", runtime.ParamLocationHeader, *params.SnykRequestId)
			if err != nil {
				return nil, err
			}

			req.Header.Set("snyk-request-id", headerParam0)
		}

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithLocation("simple", false, "user-agent", runtime.ParamLocationHeader, params.UserAgent)
		if err != nil {
			return nil, err
		}

		req.Header.Set("user-agent", headerParam1)

		var headerParam2 string

		headerParam2, err = runtime.StyleParamWithLocation("simple", false, "content-type", runtime.ParamLocationHeader, params.ContentType)
		if err != nil {
			return nil, err
		}

		req.Header.Set("content-type", headerParam2)

		if params.ContentEncoding != nil {
			var headerParam3 string

			headerParam3, err = runtime.StyleParamWithLocation("simple", false, "content-encoding", runtime.ParamLocationHeader, *params.ContentEncoding)
			if err != nil {
				return nil, err
			}

			req.Header.Set("content-encoding", headerParam3)
		}

	}

	return req, nil
}

// NewCreateUploadRevisionFilesRequestWithBody generates requests for CreateUploadRevisionFiles with any type of body
func NewCreateUploadRevisionFilesRequestWithBody(server string, orgId OrgId, uploadRevisionId UploadRevisionId, params *CreateUploadRevisionFilesParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "org_id", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "upload_revision_id", runtime.ParamLocationPath, uploadRevisionId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/orgs/%s/upload_revisions/%s/files", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "version", runtime.ParamLocationQuery, params.Version); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.SnykRequestId != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "snyk-request-id", runtime.ParamLocationHeader, *params.SnykRequestId)
			if err != nil {
				return nil, err
			}

			req.Header.Set("snyk-request-id", headerParam0)
		}

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithLocation("simple", false, "user-agent", runtime.ParamLocationHeader, params.UserAgent)
		if err != nil {
			return nil, err
		}

		req.Header.Set("user-agent", headerParam1)

		var headerParam2 string

		headerParam2, err = runtime.StyleParamWithLocation("simple", false, "content-type", runtime.ParamLocationHeader, params.ContentType)
		if err != nil {
			return nil, err
		}

		req.Header.Set("content-type", headerParam2)

		if params.ContentEncoding != nil {
			var headerParam3 string

			headerParam3, err = runtime.StyleParamWithLocation("simple", false, "content-encoding", runtime.ParamLocationHeader, *params.ContentEncoding)
			if err != nil {
				return nil, err
			}

			req.Header.Set("content-encoding", headerParam3)
		}

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListAPIVersionsWithResponse request
	ListAPIVersionsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListAPIVersionsResponse, error)

	// GetAPIVersionWithResponse request
	GetAPIVersionWithResponse(ctx context.Context, version string, reqEditors ...RequestEditorFn) (*GetAPIVersionResponse, error)

	// CreateUploadRevisionWithBodyWithResponse request with any body
	CreateUploadRevisionWithBodyWithResponse(ctx context.Context, orgId OrgId, params *CreateUploadRevisionParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateUploadRevisionResponse, error)

	CreateUploadRevisionWithApplicationVndAPIPlusJSONBodyWithResponse(ctx context.Context, orgId OrgId, params *CreateUploadRevisionParams, body CreateUploadRevisionApplicationVndAPIPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateUploadRevisionResponse, error)

	// UpdateUploadRevisionWithBodyWithResponse request with any body
	UpdateUploadRevisionWithBodyWithResponse(ctx context.Context, orgId OrgId, uploadRevisionId UploadRevisionId, params *UpdateUploadRevisionParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateUploadRevisionResponse, error)

	UpdateUploadRevisionWithApplicationVndAPIPlusJSONBodyWithResponse(ctx context.Context, orgId OrgId, uploadRevisionId UploadRevisionId, params *UpdateUploadRevisionParams, body UpdateUploadRevisionApplicationVndAPIPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateUploadRevisionResponse, error)

	// CreateUploadRevisionFilesWithBodyWithResponse request with any body
	CreateUploadRevisionFilesWithBodyWithResponse(ctx context.Context, orgId OrgId, uploadRevisionId UploadRevisionId, params *CreateUploadRevisionFilesParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateUploadRevisionFilesResponse, error)
}

type ListAPIVersionsResponse struct {
	Body                     []byte
	HTTPResponse             *http.Response
	JSON200                  *[]string
	ApplicationvndApiJSON400 *N400
	ApplicationvndApiJSON401 *N401
	ApplicationvndApiJSON404 *N404
	ApplicationvndApiJSON500 *N500
}

// Status returns HTTPResponse.Status
func (r ListAPIVersionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListAPIVersionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAPIVersionResponse struct {
	Body                     []byte
	HTTPResponse             *http.Response
	JSON200                  *map[string]interface{}
	ApplicationvndApiJSON400 *N400
	ApplicationvndApiJSON401 *N401
	ApplicationvndApiJSON404 *N404
	ApplicationvndApiJSON500 *N500
}

// Status returns HTTPResponse.Status
func (r GetAPIVersionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAPIVersionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateUploadRevisionResponse struct {
	Body                     []byte
	HTTPResponse             *http.Response
	ApplicationvndApiJSON201 *UploadRevisionPostResponse20241015
	ApplicationvndApiJSON400 *N4000
	ApplicationvndApiJSON401 *N4010
	ApplicationvndApiJSON403 *N403
	ApplicationvndApiJSON500 *N5000
}

// Status returns HTTPResponse.Status
func (r CreateUploadRevisionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateUploadRevisionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateUploadRevisionResponse struct {
	Body                     []byte
	HTTPResponse             *http.Response
	ApplicationvndApiJSON200 *UploadRevisionPostResponse20241015
	ApplicationvndApiJSON400 *N4000
	ApplicationvndApiJSON401 *N4010
	ApplicationvndApiJSON403 *N403
	ApplicationvndApiJSON404 *N4040
	ApplicationvndApiJSON500 *N5000
}

// Status returns HTTPResponse.Status
func (r UpdateUploadRevisionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateUploadRevisionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateUploadRevisionFilesResponse struct {
	Body                     []byte
	HTTPResponse             *http.Response
	ApplicationvndApiJSON400 *N4000
	ApplicationvndApiJSON401 *N4010
	ApplicationvndApiJSON403 *N403
	ApplicationvndApiJSON404 *N4040
	ApplicationvndApiJSON500 *N5000
}

// Status returns HTTPResponse.Status
func (r CreateUploadRevisionFilesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateUploadRevisionFilesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListAPIVersionsWithResponse request returning *ListAPIVersionsResponse
func (c *ClientWithResponses) ListAPIVersionsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListAPIVersionsResponse, error) {
	rsp, err := c.ListAPIVersions(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListAPIVersionsResponse(rsp)
}

// GetAPIVersionWithResponse request returning *GetAPIVersionResponse
func (c *ClientWithResponses) GetAPIVersionWithResponse(ctx context.Context, version string, reqEditors ...RequestEditorFn) (*GetAPIVersionResponse, error) {
	rsp, err := c.GetAPIVersion(ctx, version, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAPIVersionResponse(rsp)
}

// CreateUploadRevisionWithBodyWithResponse request with arbitrary body returning *CreateUploadRevisionResponse
func (c *ClientWithResponses) CreateUploadRevisionWithBodyWithResponse(ctx context.Context, orgId OrgId, params *CreateUploadRevisionParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateUploadRevisionResponse, error) {
	rsp, err := c.CreateUploadRevisionWithBody(ctx, orgId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateUploadRevisionResponse(rsp)
}

func (c *ClientWithResponses) CreateUploadRevisionWithApplicationVndAPIPlusJSONBodyWithResponse(ctx context.Context, orgId OrgId, params *CreateUploadRevisionParams, body CreateUploadRevisionApplicationVndAPIPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateUploadRevisionResponse, error) {
	rsp, err := c.CreateUploadRevisionWithApplicationVndAPIPlusJSONBody(ctx, orgId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateUploadRevisionResponse(rsp)
}

// UpdateUploadRevisionWithBodyWithResponse request with arbitrary body returning *UpdateUploadRevisionResponse
func (c *ClientWithResponses) UpdateUploadRevisionWithBodyWithResponse(ctx context.Context, orgId OrgId, uploadRevisionId UploadRevisionId, params *UpdateUploadRevisionParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateUploadRevisionResponse, error) {
	rsp, err := c.UpdateUploadRevisionWithBody(ctx, orgId, uploadRevisionId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateUploadRevisionResponse(rsp)
}

func (c *ClientWithResponses) UpdateUploadRevisionWithApplicationVndAPIPlusJSONBodyWithResponse(ctx context.Context, orgId OrgId, uploadRevisionId UploadRevisionId, params *UpdateUploadRevisionParams, body UpdateUploadRevisionApplicationVndAPIPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateUploadRevisionResponse, error) {
	rsp, err := c.UpdateUploadRevisionWithApplicationVndAPIPlusJSONBody(ctx, orgId, uploadRevisionId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateUploadRevisionResponse(rsp)
}

// CreateUploadRevisionFilesWithBodyWithResponse request with arbitrary body returning *CreateUploadRevisionFilesResponse
func (c *ClientWithResponses) CreateUploadRevisionFilesWithBodyWithResponse(ctx context.Context, orgId OrgId, uploadRevisionId UploadRevisionId, params *CreateUploadRevisionFilesParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateUploadRevisionFilesResponse, error) {
	rsp, err := c.CreateUploadRevisionFilesWithBody(ctx, orgId, uploadRevisionId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateUploadRevisionFilesResponse(rsp)
}

// ParseListAPIVersionsResponse parses an HTTP response from a ListAPIVersionsWithResponse call
func ParseListAPIVersionsResponse(rsp *http.Response) (*ListAPIVersionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListAPIVersionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []string
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N400
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N401
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest N500
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON500 = &dest

	}

	return response, nil
}

// ParseGetAPIVersionResponse parses an HTTP response from a GetAPIVersionWithResponse call
func ParseGetAPIVersionResponse(rsp *http.Response) (*GetAPIVersionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAPIVersionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest map[string]interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N400
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N401
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest N500
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON500 = &dest

	}

	return response, nil
}

// ParseCreateUploadRevisionResponse parses an HTTP response from a CreateUploadRevisionWithResponse call
func ParseCreateUploadRevisionResponse(rsp *http.Response) (*CreateUploadRevisionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateUploadRevisionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest UploadRevisionPostResponse20241015
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N4000
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N4010
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest N403
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest N5000
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON500 = &dest

	}

	return response, nil
}

// ParseUpdateUploadRevisionResponse parses an HTTP response from a UpdateUploadRevisionWithResponse call
func ParseUpdateUploadRevisionResponse(rsp *http.Response) (*UpdateUploadRevisionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateUploadRevisionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UploadRevisionPostResponse20241015
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N4000
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N4010
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest N403
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N4040
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest N5000
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON500 = &dest

	}

	return response, nil
}

// ParseCreateUploadRevisionFilesResponse parses an HTTP response from a CreateUploadRevisionFilesWithResponse call
func ParseCreateUploadRevisionFilesResponse(rsp *http.Response) (*CreateUploadRevisionFilesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateUploadRevisionFilesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N4000
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N4010
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest N403
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N4040
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest N5000
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON500 = &dest

	}

	return response, nil
}
